FROM oven/bun:1

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./apps/backend ./apps/backend

RUN bun install

EXPOSE 8080

# Generate Prisma client and start app
CMD bun run db:generate && bun run start
